/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.pestannas.formas;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import uam.pvoe.sw.menu.clases.Material;
import uam.pvoe.sw.menu.operaciones.AgregarMaterial;

/**
 *
 * @author ALEXISGARCIA
 */
public class AltaMaterial extends javax.swing.JPanel {

    
    boolean validacion[] = new boolean[5];
    /**
     * Creates new form AltaMaterial
     */
    public AltaMaterial() {
        initComponents();
        radioButtons();
        comboBox();
    }
    /*
    private void validaciones(){
        for(int i = 0; i<5; i++){
            validacion[i] = false;
        }
    }
    */
    private void radioButtons(){
        bgroupTipoMaterial.add(rbLibro);
        bgroupTipoMaterial.add(rbPelicula);
        bgroupTipoMaterial.add(rbRevista);
        
        rbRevista.setSelected(true);
    }
    
    private void comboBox(){
        cmbTema.removeAllItems();
        cmbTema.addItem("Seleccion una opción");
        cmbTema.addItem("CBI");
        cmbTema.addItem("CyAD");
        cmbTema.addItem("CSH");
    }

    private void limpiarDatos(){
        rbRevista.setSelected(true);
        txtAutor.setText("");
        txtEjemplares.setText("");
        txtLote.setText("");
        txtTitulo.setText("");
        
        comboBox();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroupTipoMaterial = new javax.swing.ButtonGroup();
        lblAlta = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblTipoMaterial = new javax.swing.JLabel();
        rbRevista = new javax.swing.JRadioButton();
        rbLibro = new javax.swing.JRadioButton();
        rbPelicula = new javax.swing.JRadioButton();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblTema = new javax.swing.JLabel();
        cmbTema = new javax.swing.JComboBox<>();
        lblEjemplares = new javax.swing.JLabel();
        txtEjemplares = new javax.swing.JTextField();
        lblLote = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));

        lblAlta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAlta.setText("Dar de Alta un Nuevo Material");

        lblSubtitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubtitulo.setText("Ingrese los datos:");

        lblTipoMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoMaterial.setText("Tipo de Material");

        rbRevista.setText("Revista");
        rbRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRevistaActionPerformed(evt);
            }
        });

        rbLibro.setText("Libro");
        rbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLibroActionPerformed(evt);
            }
        });

        rbPelicula.setText("Película");
        rbPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPeliculaActionPerformed(evt);
            }
        });

        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAutor.setText("Autor");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setText("Título");

        lblTema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTema.setText("Área (tema)");

        cmbTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEjemplares.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEjemplares.setText("Cantidad de ejemplares adquiridos");

        lblLote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLote.setText("Clave del lote");

        btnConfirmar.setText("Confirmar Registro");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(lblAlta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo)
                            .addComponent(lblLote)
                            .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutor)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnConfirmar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTema)
                                    .addComponent(lblTipoMaterial)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbRevista)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbLibro)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbPelicula))
                                    .addComponent(txtAutor)
                                    .addComponent(txtTitulo)
                                    .addComponent(cmbTema, 0, 471, Short.MAX_VALUE)
                                    .addComponent(lblEjemplares)
                                    .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(btnLimpiar)))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblAlta)
                .addGap(24, 24, 24)
                .addComponent(lblSubtitulo)
                .addGap(29, 29, 29)
                .addComponent(lblTipoMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRevista)
                    .addComponent(rbLibro)
                    .addComponent(rbPelicula))
                .addGap(18, 18, 18)
                .addComponent(lblTema)
                .addGap(5, 5, 5)
                .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAutor)
                .addGap(8, 8, 8)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblEjemplares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnLimpiar))
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void rbRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRevistaActionPerformed
        comboBox();
    }//GEN-LAST:event_rbRevistaActionPerformed

    private void rbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLibroActionPerformed
        comboBox();
    }//GEN-LAST:event_rbLibroActionPerformed

    private void rbPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPeliculaActionPerformed
        comboBox();
    }//GEN-LAST:event_rbPeliculaActionPerformed

    public boolean isInteger(String numero){
        try{
            Integer.parseInt(numero);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        AgregarMaterial agregar = new AgregarMaterial();
        
        //Tipo de material:
        Enumeration<AbstractButton> btnGrpTipoMaterial = bgroupTipoMaterial.getElements();
        String tipoMaterial = "";
        while(btnGrpTipoMaterial.hasMoreElements()){
            JRadioButton btnAux = (JRadioButton) btnGrpTipoMaterial.nextElement();
            if(btnAux.isSelected()){
                tipoMaterial = btnAux.getText();
                break;
            }
        }
        
        
        if(cmbTema.getSelectedIndex() == 0){ //Aqui podriamos agregar MAS condiciones para aniadir los materiales
            JOptionPane.showMessageDialog(null,"Selecciona un tema!"); 
        } else{
            String tema = (String) cmbTema.getSelectedItem();
            
            if(txtAutor.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null,"Digite el nombre del autor"); 
            } else{
                String autor = txtAutor.getText(); 
                
                if(txtTitulo.getText().compareTo("") == 0){
                    JOptionPane.showMessageDialog(null,"Digite el titulo de la obra"); 
                } else{
                    String titulo = txtTitulo.getText(); //3
                    
                    if((isInteger(txtEjemplares.getText()) == false)){
                        JOptionPane.showMessageDialog(null,"La cantidad de ejemplares debe de ser un numero"); 
                    } else{
                         int cantidadEjemplares = Integer.parseInt(txtEjemplares.getText()); //5 
                         
                         if(txtLote.getText().length() != 10){
                             JOptionPane.showMessageDialog(null,"La clave de el Lote debe de tener 10 caracteres");
                         } else{
                            String claveLote = txtLote.getText(); //6
                            
                            Material material = new Material(tipoMaterial,titulo,autor,tema,cantidadEjemplares,claveLote);

                            agregar.agregarNuevo(material); //Agregamos el material al archivo que corresponda
                            limpiarDatos();
                         }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroupTipoMaterial;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbTema;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEjemplares;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTipoMaterial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbLibro;
    private javax.swing.JRadioButton rbPelicula;
    private javax.swing.JRadioButton rbRevista;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEjemplares;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
