
package uam.pvoe.sw.pestannas.formas;

import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import uam.pvoe.sw.menu.comparitido.Compartido;

/**
 *
 * @author ALEXISGARCIA
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        mensajeBienvenida();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    private void mensajeBienvenida(){
        //Mensaje de Bienvenida
        lblMensajeBienvenida.setText("Bienvenido " + Compartido.loginUsuario);
       
        
        //Fecha
        String pattern = "MM/dd/yyyy HH:mm:ss";
        // Create an instance of SimpleDateFormat used for formatting 
        // the string representation of date according to the chosen pattern
        DateFormat df = new SimpleDateFormat(pattern);

        // Get the today date using Calendar object.
        Date today = Calendar.getInstance().getTime();        
        // Using DateFormat format method we can create a string 
        // representation of a date with the defined format.
        String todayAsString = df.format(today);

        lblFecha.setText(todayAsString);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedContenedor = new javax.swing.JTabbedPane();
        tabbedMenu = new javax.swing.JTabbedPane();
        tabbedAlta = new javax.swing.JTabbedPane();
        tabbedBaja = new javax.swing.JTabbedPane();
        tabbedConsulta = new javax.swing.JTabbedPane();
        lblMensajeBienvenida = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedContenedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabbedContenedor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedContenedorStateChanged(evt);
            }
        });

        tabbedMenu.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tabbedContenedor.addTab("Bienvenido", tabbedMenu);

        tabbedAlta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tabbedContenedor.addTab("Dar de alta un material", tabbedAlta);

        tabbedBaja.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tabbedContenedor.addTab("Dar de baja un material", tabbedBaja);

        tabbedConsulta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tabbedContenedor.addTab("Consultar material", tabbedConsulta);

        lblMensajeBienvenida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1414, Short.MAX_VALUE))
                    .addComponent(tabbedContenedor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensajeBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tabbedContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tabbedContenedorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedContenedorStateChanged
        int pestannaElegida = 0;
        pestannaElegida = tabbedContenedor.getSelectedIndex();
        
        switch(pestannaElegida){
            case 0:
                
                Component compBienvenida = new Bienvenida();
                tabbedContenedor.setComponentAt(0, compBienvenida);
                break;
            case 1:
                Component datosArticulo = new AltaMaterial();
                tabbedContenedor.setComponentAt(1, datosArticulo);
                break;
            case 2:
                Component compNuevoArticulo = new BajaMaterial();
                tabbedContenedor.setComponentAt(2, compNuevoArticulo);
                break;
            /*case 3:
                Component compNuevaRevista = new NuevaRevista();
                jTabbedPane1.setComponentAt(3, compNuevaRevista);
                break;*/
        }
    }//GEN-LAST:event_tabbedContenedorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JTabbedPane tabbedAlta;
    private javax.swing.JTabbedPane tabbedBaja;
    private javax.swing.JTabbedPane tabbedConsulta;
    private javax.swing.JTabbedPane tabbedContenedor;
    private javax.swing.JTabbedPane tabbedMenu;
    // End of variables declaration//GEN-END:variables
}
